import React from 'react';
import { 
  LayoutDashboard, 
  Home, 
  Users, 
  Calculator, 
  MessageSquare, 
  Zap, 
  Settings,
  Search,
  Bell,
  Menu,
  X,
  Send,
  Mic,
  Building2,
  DollarSign,
  TrendingUp,
  Briefcase,
  CheckCircle2,
  MoreVertical,
  Heart,
  Share2,
  ArrowRight,
  PlayCircle,
  Lock,
  Sparkles
} from 'lucide-react';

export const ICONS = {
  Dashboard: <LayoutDashboard size={20} />,
  Feed: <Home size={20} />,
  Network: <Users size={20} />,
  Toolkit: <Calculator size={20} />,
  Chat: <MessageSquare size={20} />,
  AI: <Zap size={20} />,
  Settings: <Settings size={20} />,
  Search: <Search size={18} />,
  Bell: <Bell size={20} />,
  Menu: <Menu size={24} />,
  Close: <X size={24} />,
  Send: <Send size={18} />,
  Mic: <Mic size={18} />,
  Building: <Building2 size={16} />,
  Dollar: <DollarSign size={16} />,
  Trend: <TrendingUp size={16} />,
  Case: <Briefcase size={16} />,
  Check: <CheckCircle2 size={16} />,
  More: <MoreVertical size={16} />,
  Heart: <Heart size={18} />,
  Share: <Share2 size={18} />,
  ArrowRight: <ArrowRight size={20} />,
  Play: <PlayCircle size={24} />,
  Lock: <Lock size={14} />,
  Sparkles: <Sparkles size={16} />
};

export const MOCK_DEALS = [
  {
    id: '1',
    address: '1243 Maple Ave',
    city: 'Atlanta',
    state: 'GA',
    zip: '30303',
    price: 145000,
    arv: 260000,
    repairs: 45000,
    assignmentFee: 15000,
    status: 'Assigned',
    type: 'Single Family',
    financeType: 'Cash',
    imageUrl: 'https://picsum.photos/800/600?random=1',
    postedBy: 'Marcus Invests',
    postedAt: '2h ago',
    likes: 24
  },
  {
    id: '2',
    address: '882 Sunset Blvd',
    city: 'Austin',
    state: 'TX',
    zip: '78701',
    price: 210000,
    arv: 350000,
    repairs: 10000,
    assignmentFee: 25000,
    status: 'Under Contract',
    type: 'Multi Family',
    financeType: 'Subject-To',
    imageUrl: 'https://picsum.photos/800/600?random=2',
    postedBy: 'Sarah Wholesales',
    postedAt: '5h ago',
    likes: 156
  },
  {
    id: '3',
    address: '445 Oak Drive',
    city: 'Phoenix',
    state: 'AZ',
    zip: '85001',
    price: 295000,
    arv: 410000,
    repairs: 30000,
    assignmentFee: 20000,
    status: 'Lead',
    type: 'Single Family',
    financeType: 'Novation',
    imageUrl: 'https://picsum.photos/800/600?random=3',
    postedBy: 'Elite Homes',
    postedAt: '1d ago',
    likes: 42
  }
] as const;
